---
title: "testing performance package"
author: "Ben Anderson"
date: "25/04/2022"
output:
  html_document: default
  pdf_document: default
---

# `Performance` package

https://easystats.github.io/performance/

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(performance)

mtcars <- mtcars
```

Use some mtcars data

```{r cars}
summary(mtcars)
```

# Make a model, any model

For example:

```{r qsec}
qsecModel <- lm(formula = qsec ~ carb + disp + wt, data = mtcars)

qsecModel

summary(qsecModel)
```

# Check model `performance`

```{r qsecCheck, fig.cap="Testing the model"}

performance::check_model(qsecModel, 
                         panel = FALSE # create 1 plot per check (otherwise we get them as smaller panels)
                         )

```


> Very Nice...

# Use `see` to look-see the model

```{r plotModel}
library(see)
library(parameters)
library(ggplot2)

plot(parameters::parameters(qsecModel)) +
  ggplot2::labs(title = "A Dot-and-Whisker Plot")
```
> Oh yes, we quite like that too...

# The end